version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.10.0
    - 4.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
    - 3.3.0
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.1.0
    - 9.1.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 4.2.0
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.30.2
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.7.3
    - 12.8.3
    - 13.0.0
    - 13.0.16
  - dependency-name: cypress
    versions:
    - 6.8.0
  - dependency-name: testcafe-react-selectors
    versions:
    - 4.1.5
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.11.0
    - 3.0.1
    - 3.1.0
  - dependency-name: postcss
    versions:
    - 8.2.8
  - dependency-name: gatsby
    versions:
    - 2.32.0
    - 3.0.4
  - dependency-name: gatsby-plugin-purgecss
    versions:
    - 6.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: gatsby-source-graphql
    versions:
    - 2.14.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.12.0
  - dependency-name: gatsby-plugin-postcss
    versions:
    - 3.7.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: start-server-and-test
    versions:
    - 1.12.0
